remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: keystoneDB
description: A relational DBMS built upon persistent key-value storage
show_downloads: true
github:
  repository_url: https://github.com/SumitKumar-17/keystoneDB
  zip_url: https://github.com/SumitKumar-17/keystoneDB/zipball/main
  tar_url: https://github.com/SumitKumar-17/keystoneDB/tarball/main