source "https://rubygems.org"

gem "jekyll", "~> 4.2.2"
gem "jekyll-remote-theme", "~> 0.4.3"
gem "jekyll-sass-converter", "~> 2.2.0"
gem "webrick", "~> 1.7"
gem "rubyzip", "~> 2.3.0"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end
